name: Lintian-brush

on:
  workflow_dispatch:
  schedule:
    # Schedule to run at midnight every day
    - cron: '0 0 * * *'

jobs:
  lintian-brush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
         sudo apt-get -y install lintian-brush
         cd duckdb-*
         lintian-brush
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: lintian-brush/patch
          title: 'Update debian packaging'
          body: |
            Automated changes by [lintian-brush][1]
            [1]: https://salsa.debian.org/jelmer/lintian-brush
