on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - run: sudo apt install devscripts ninja-build cmake dh-cmake

    - working-directory: duckdb_ppa
      run: dpkg-buildpackage
