on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - run: sudo apt install devscripts ninja-build cmake dh-cmake

    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@main
      with:
        variant: sccache
        key: ${{ github.job }}

    - run: dpkg-parsechangelog >> $GITHUB_STEP_SUMMARY
      working-directory: duckdb_ppa

    - working-directory: duckdb_ppa
      run: dpkg-buildpackage
      env:
        DEB_BUILD_OPTIONS: sccache

    - run: sudo dpkg -i duckdb_0.10.0-*.deb

    - run: duckdb --version

    # - run: man duckdb
