on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      matrix:
        duckdb_version: ['0.10.0']

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - run: sudo apt install devscripts ninja-build build-essential cmake dh-cmake

    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@main
      with:
        variant: sccache
        key: ${{ github.job }}

    - run: make setup

    - run: dpkg-parsechangelog >> $GITHUB_STEP_SUMMARY
      working-directory: duckdb-${{ matrix.duckdb_version }}

    - name: dpkg-buildpackage
      working-directory: duckdb-${{ matrix.duckdb_version }}
      run: dpkg-buildpackage --unsigned-source --unsigned-changes --unsigned-buildinfo --build=binary
      env:
        DEB_BUILD_OPTIONS: "parallel=5 sccache"

    - run: sudo dpkg -i *.deb

    - run: duckdb --version

    # - run: man duckdb

    - run: ls

    - uses: actions/upload-artifact@v4
      with:
        path: duckdb_${{ matrix.duckdb_version }}-*

