on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      matrix:
        release: [focal, jammy, mantic, noble]
        duckdb_version: ['0.10.0']

    runs-on: ubuntu-latest

    env:
      SCCACHE_GHA_ENABLED: "true"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: install deps
      run: |
        sudo apt update -y
        sudo apt install devscripts ninja-build build-essential cmake dh-cmake

    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@main
      with:
        variant: sccache
        key: ${{ github.job }}

    - run: make setup

    - run: dpkg-parsechangelog >> $GITHUB_STEP_SUMMARY
      working-directory: duckdb-${{ matrix.duckdb_version }}

    - working-directory: duckdb-${{ matrix.duckdb_version }}
      run: debuild --unsigned-source --unsigned-changes --unsigned-buildinfo --build=binary
      env:
        DEB_BUILD_OPTIONS: "parallel=5 sccache"

    - run: sudo dpkg -i *.deb

    - run: duckdb --version

    - run: man duckdb

    - run: ls

    - uses: actions/upload-artifact@v4
      with:
        path: |
          duckdb_${{ matrix.duckdb_version }}*
          libduckdb-dev_${{ matrix.duckdb_version }}*
          libduckdb_${{ matrix.duckdb_version }}*
          libduckdb-dbgsym_${{ matrix.duckdb_version }}*
          duckdb-dbgsym_${{ matrix.duckdb_version }}*
        name: ${{ matrix.release }}

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          separate-directories: true
