on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      matrix:
        duckdb_version: ['0.10.0']

    runs-on: ubuntu-latest

    env:
      SCCACHE_GHA_ENABLED: "true"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - run: sudo apt install devscripts ninja-build build-essential cmake dh-cmake

    - run: wget https://api.github.com/repos/duckdb/duckdb/tarball/refs/tags/v${{ matrix.duckdb_version }} -O duckdb_${{ matrix.duckdb_version }}.orig.tar.gz

    - uses: Mozilla-Actions/sccache-action@v0.0.4
            
    - run: dpkg-parsechangelog >> $GITHUB_STEP_SUMMARY
      working-directory: duckdb_ppa

    - working-directory: duckdb_ppa
      run: dpkg-buildpackage
      env:
        DEB_BUILD_OPTIONS: "parallel=5 sccache"


    - run: sudo dpkg -i *.deb

    - run: duckdb --version

    # - run: man duckdb
